
spring:
  datasource:
    url: jdbc:mysql://mymysql:3306/note?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: myes:9300
  redis:
    host: myredis
    port: 6379
  kafka:
    bootstrap-servers: mykafka:9092


logging:
  file:
    name: log.txt
  level:
    root:
      info
    com.xxywebsite.mynote.mapper:
      debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#debug: true
server:
  port: 8082



